DB_HOST="localhost"
DB_NAME="8core5_scanner"
DB_USER="8core5_scanner"
DB_PASS="c7SDuzWWSl2x"
DB_CHARSET="utf8mb4"
echo >> /root/scanner-db.conf


















































































































































































































































































































